### ISSUE TITLE
实现树形表格控件

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#10]
可参考资源：
[treegrid](http://maxazan.github.io/jquery-treegrid/)
![image](https://cloud.githubusercontent.com/assets/8817002/26665579/4ee79654-46cd-11e7-8ffe-9e5c944ea457.png)

树形表格用途广泛，设备列表，业务平台列表都需要使用

数据存储暂时采用mongodb

**Comment by chenzhq** [comment]
这个组件已经实现了吗？ @yanms719

**Comment by yanms719** [comment]
可以查看最新tab.html页面，样式有的，数据存储我还没考虑到这一步

**Comment by chenzhq** [comment]
我看了你的实现方式，使用的是SemanticUI的accordion，这种实现结果有个很明显的问题，上下列的文字没有对齐，能不能调整？

**Comment by yanms719** [comment]
文字已调整

**Comment by chenzhq** [comment]
有没有push？如果push了，带上commit的链接或者hash值
