### ISSUE TITLE
使用semanticUI重构页面

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#12]
任务如下：
- [x] 完成系统页面框架
- [x] 替换登录页面
- [x] 逐步删除LayUI的遗留文件，整理semanticUI的静态文件

暂时不用过多考虑动画效果以及细节的优化，先把总体结构搭建起来，快速地把之前的页面布局移植到新页面。
控制提交的粒度

0605补充：
- [x] 重构可以参考stagb，**按需添加**jquery插件，**禁止直接增加所有的静态文件，包括js，css，img等**
- [x] 将所有需要使用的jquery插件整理成一份**简单**的文档（可以直接在本issue下补充，也可以重新开一个issue）；内容包括：插件名+用途（一两句话）+官网地址（或者github地址）+补充。部分特定页面下会引用单独的js文件，我们需要参照这些文件写自己的代码，这些文件的增加需要在提交信息中描述清楚。

**介绍示例**
pace.js 
用于展示页面加载的进度条插件
[官网地址](http://github.hubspot.com/pace/docs/welcome/)

**Comment by yanms719** [comment]
jquery-3.2.1.min.js用于jquery调用，地址https://code.jquery.com
semantic.js用于框架调用，地址https://semantic-ui.qyears.com
echarts.min.js用于图表调用，地址http://echarts.baidu.com/
http://rapapi.org/rap.plugin.js?projectId=19544，用于模拟服务器ajax数据传输

**Comment by chenzhq** [comment]
你列的这几个是主要的，但不是最需要整理的，这里主要整合各类插件的用途

**Comment by yanms719** [comment]
下载的那个参考模板里面的js没有借用，看过一个菜单相关联的js就有3个，写的很有些复杂。这几个主要的JS就是项目目前用的全部。

**Comment by chenzhq** [comment]
@zhongstar 
为什么reopen这个issue？

**Comment by zhongstar** [comment]
@chenzhq 
拖错了，拖回关闭状态了。
