### ISSUE TITLE
三种类型对象的各个属性的定义及其值的获取方式

### ISSUE THREAD

**Issue by zhongstar** [chenzhq/WsMonitor#16]
## 说明

1. 三种类型（业务平台、主机、监控点）对象list传输到`dashboard`页面上的方式建议采用**异步调用传输**
2. 项目中构建对象类型的方式应该为DTO，定义名称为BriefHostDTO、BriefPointDTO、BriefPlatformDTO

## BriefHostDTO对象
String ip，String hostId，String name，String state,String type；
注意state为String，不是List<String>,rap中接口定义为list类型，不清楚为什么；
### 获取方式
**ip**:根据设定`selectInterfaces : ip`，得到的是list interfaces,获取方式取list interfaces的第一个值，但是这样就要再建一个interface实体了；
**state**:
**type**:
## BriefPointDTO对象
Datetime lastChange,      Integer  lastData,   String name,   String state
### 获取方式：
**lastChange**：取该点下的所有监控项，循环遍历取出最新时间
**lastData**：
**state**：
## BriefPlatformDTO对象
Integer availability,    String name ,   Integer problemNum ,    String state
### 获取方式：
**availability**
**problemNum** ：调用countStatusService,这样就是fetchBriefService 调用了count Service
**state**：

 @chenzhq 总结以上，发现主机的业务实体组装还是有一定的困难，给个建议看怎么处理为好！ #15

**Comment by chenzhq** [comment]
@zhongstar 
帮你把格式简单调整了一下
### 回答如下
1. rap中的主机state定义有问题，应该是String，因为模拟数据结果没区别，所以没发现
2. 构建`BriefPlatformDTO`对象（包括`problemNum`）应该是`FetchBriefServiceImpl`的一个（或多个）方法，不涉及其它Service的相互调用
3. 组装的困难是什么
---
@yanms719 
另外，github大多采用Markdown的格式，这是一个轻量级的书写规范，**强烈建议**学习一下，github已经提供了一个很简洁的[说明](https://guides.github.com/features/mastering-markdown/)

**Comment by zhongstar** [comment]
@chenzhq 关于#16 的问题周五商讨的结果做一个总结和我自己提出的想法如下： 
**1、构建对象，两类对象：**
**BriefHostDTO、BriefPointDTO、BriefPlatformDTO**这类对象用于接收response的传输对象；
**BriefHostVO、BriefPointVO、BriefPlatformVO**，这三个对象才应该是上面#16中提到的传输到页面上的对象，字段名称和接口中定义的匹配。如下为映射到**BriefHostDTO**对象类型的response的一个host
```     
{
      "hostid": "10233",
      "host": "ZKF_Win_178",
      "parentTemplates": [
        {
          "templateid": "10202",
          "host": "Windows_OS_Agent"
        }
      ],
      "interfaces": [
        {
          "ip": "145.170.24.92"
        }
      ]
    }
```
**2、获取方式**
**response与BriefHostDTO对象映射获取方式：**
host.get 的 param中选择： "selectInterfaces":["ip"],"output":["hostid","host"],"selectParentTemplates":["templateid","host"]

**BriefHostVO获取方式**：主要关注state，type，ip；
**state:** 
       step1:取BriefHostDTO 类型所有主机alllist以及问题主机problemlist;
       step2:根据得到的问题主机的hostids给VO类型的state属性赋值；
**type:**
      step1:取BriefHostDTO 类型所有主机alllist;
      step2:取所有模板并附带模板群组  templatelist ，"selectGroups":["groupid","name"],"output":["host","templateid"，"name"]，得到如下response，映射对象BriefTemplateDTO (需要新建)
```
{
      "host": "Whstone_DB_MySQL",
      "templateid": "10186",
      "name": "Whstone_DB_MySQL",
      "groups": [
        {
          "groupid": "25",
          "name": "自建模版"
        }
      ]
    }	
```

step3:根据alllist 的 templateid  去匹配 templatelist 的 templateid  ，匹配上的给VO类型的type赋值groups 的name，前提条件是主机--模板--模板群组为1对1对1映射；
**ip:**
    step1:取BriefHostDTO 类型所有主机alllist;
    step2:循环取alllist 的 interfaces 的第一个interface的ip赋给 VO类型的ip；


**综上，取三个lis**t：<HostDTO>allList, <HostDTO>problemList,<TemplateDTO>allList;
           新建<HostVO>vohosts,循环allList，取problemList的hostids，分别给vohost对象赋值组装成list返回即可。
