### ISSUE TITLE
前端插件使用说明

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#18]
之前说过，每使用一个插件或框架，需要同步更新对应的使用说明，一直没有结果。

#12 中引用的几个就放在那里，其它的插件说明添加在此issue下。

保证先有文档，再有代码提交。

**Comment by yanms719** [comment]
折叠表格(treegirt)插件：
../static/js/jquery.treegrid.js
../static/css/jquery.treegrid.css
参考官网：http://maxazan.github.io/jquery-treegrid/

**Comment by yanms719** [comment]
提示框（lobibox）插件：
../static/js/notifications.js
../static/css/lobibox.css
参考官网：http://lobianijs.com/site/lobibox

**Comment by yanms719** [comment]
数据表格（datatable）插件：
../static/js/jquery.dataTables.js
../static/js/custom-datatable.js
参考官网：https://www.datatables.net/

**Comment by yanms719** [comment]
拖拽（Gridly）插件：
../static/css/jquery.gridly.css
../static/js/jquery.gridly.js
参考官网：http://ksylvest.github.io/jquery-gridly/

**Comment by yanms719** [comment]
静态窗口（监控点）js封装：
../static/js/pointModal.js
辅助工具（告警信息、判断字符串长度）js封装：
../static/js/assistantTool.js
