### ISSUE TITLE
设备监控的页面设计

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#19]
保持思考，提出自己的创意和想法
具体的功能需求可以查看 #17 

---
## 树形折叠表格

- 在没有更合适的选择之前，使用 #10 中提到的插件，设计并实现出我们需要的表格。
- 弄清楚如何异步加载数据，以及数据的格式，补充此issue
- 将**使用方法**，及实现过程中遇到的任何问题，**形成文档**，补充在此issue下

**Comment by yanms719** [comment]
树形折叠表格，使用datatable和treegird两个插件结合的方法；
数据的格式，使用的是datatable自带的json数据格式。
