### ISSUE TITLE
评估LayUI

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#2]
## 重新评估LayUI
这个框架不仅定义了UI层面的编码规则，也统一了JS的模块规范，上手比较快；但缺点也很明显，框架比较新，维护人员较少，所以现在组件的覆盖面**太少**，在已有的组件中，也有不少基本功能没有实现，作者已经明确说明后期才会考虑增加。
相比较，其实有其它更成熟的框架可以参考，除去bootstrap，还有semantic-ui，fundation，以及一些国产框架。你需要仔细评估一下使用LayUI是否合适。

_评估结果直接回复_

**Comment by chenzhq** [comment]
@yanms719 评估结果如何？
如果换UI框架，难度多大，大概需要多长时间？

**Comment by yanms719** [comment]
一周 内 换完

**Comment by chenzhq** [comment]
这个issue已经close
新的issue在 #12
