### ISSUE TITLE
优化api调用的逻辑

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#20]
## 要求

- 充分考虑缓存和数据重用，修改部分数据的获取逻辑，减少api调用的次数
- 减少dashboard页面数据加载时间
- 先写设计文档，再重构代码

## 文档

- 哪些数据可以使用缓存
- 重构后，数据获取的方法和步骤

**Comment by zhongstar** [comment]
**方法调用关系图**
[脑图](http://naotu.baidu.com/file/5f7f9e45a04842654aed79e0b9aa7e43?token=ed9d6c03dc067ab9)

![dashbaordcontroller](https://user-images.githubusercontent.com/18592877/27568091-8e101720-5b22-11e7-97d7-c4ed979f8926.png)


根据脑图分析做一下两点改动：

**数据获取优化**
1、针对一个service里面重复调用manager用变量存储，但是有个问题，如下图：
![image](https://user-images.githubusercontent.com/18592877/27567197-ee433e8e-5b1c-11e7-8fc8-6b94bc24f2a3.png)

**listDashboardPlatform**调用的两个方法里面包含相同的**manager**，变量无法实现,
建议处理方式：将triggerManager.getProblemTriggerIds()抽离出来通过参数传入，在**listDashboardPlatform** 的**service**层先去调用**triggerManager.getProblemTriggerIds()**，再传入**listProblemHost**()和**listProblemPoint**()做相关处理。

2、针对获取所有的对象类型的数据考虑可以使用缓存来减少对**api**的访问次数，但是也存在问题，例如获取所有业务平台**listPlatform**，筛选条件中有.**setMonitoredHosts**(true)、.**setRealHosts**(true)，这种筛选在更改配置之后数据有所变动，这种需要考虑；

根据分析可以设置缓存的方法有（获取关于状态的一律不能用缓存，获取问题触发器的一律不能用缓存）：**listHost**()、**listAllTemplate**()、**listPlatform**()、**listHost**()、**listPoint**()

**工程结构重构**
    根据脑图的结构分析，关于**manager**层的处理，我建议：

**service层**
业务相关service：三个**countstate**、四个list。**countHostState**()... **listDashBoardHosts**...

**manager层**
基础调用manager：如**hostManager：countHostState**()、**countProblemHost**()、**listHost**()【这个放到manager层之后改名为**listAllHost**()】、**listProblemHost**()、同时保留原来的**manager**的**list**和**count**方法做内部自己调用。
