### ISSUE TITLE
页面调整

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#21]
> 此issue纪录页面中的各种问题，包括布局，数据加载和细节等问题。

**问题修复后，附上提交的链接或hash值**

## dashboard页面

- [x] 异步获取数据的表格，在数据加载前后，表头的位置有变化

- [x] 异步获取数据的表格在数据加载之前，增加loading动画

- [x] 每个tab页，需要有一个min-height

- [x] 点击左侧菜单进入对应的页面后，被点击的菜单项样式要有一定的变化

- [x] 调整饼图高度，label有时会被遮挡

- [x] 问题列表一页显示10行

- [x] 点击第一个tab页上的饼图，跳转到相应页面上，并给出对应的筛选结果

- [x] 业务系统和设备列表中的表头，**问题数／问题总数**，表述不正确，一个是问题数，一个是总数

## 代码

- [x] 使用Datatable ajax的[API异步获取数据](https://www.datatables.net/manual/ajax)，除非有不能克服的障碍，否则不要自己写硬代码。_修改包括dashboard的三类对象表格和设备监控表格的数据_

**Comment by yanms719** [comment]
462f6641988164f59d82673d5b2dd08ef85cfa7b
tab页添加min-height；表格loading动画、简化分页 ；

**Comment by yanms719** [comment]
8800079156c1f80abda2211351c37698b08a44c7
tab页固定表头的位置

**Comment by yanms719** [comment]
734737e

**Comment by yanms719** [comment]
734737e76f581fc9ee3dbfaab69dbdce6b720481

**Comment by chenzhq** [comment]
你得说明哪次提交对应什么内容，修改一下上面三条评论

**Comment by yanms719** [comment]
c0f67f3570cc1c65656b7668bd24bcb73ff113ee
使用Datatable ajax的API异步获取数据

**Comment by yanms719** [comment]
bd1e53a4b3918022bea1e43976ea195a94233eec
使用Datatable ajax的API异步获取数据(设备监控表格)

**Comment by yanms719** [comment]
9053629c35a432732dd898f14c4dcf9963ff23e9
调整饼图高度，label有时会被遮挡;
 业务系统和设备列表中的表头，问题数／问题总数，表述不正确，一个是问题数，一个是总数;
问题列表一页显示10行

**Comment by yanms719** [comment]
501a8dad053d75d2e968cc5291da7087b2dc1530
点击第一个tab页上的饼图，跳转到相应页面上，并给出对应的筛选结果
