### ISSUE TITLE
设备监控树形表格数据存储方案

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#22]
使用Monogdb，只存储设备的所属结构数据，即属于哪个组。不存储设备和监控点等对象的具体配置信息。文档初步结构：

``` json
{
	"_id": "xxx",
	"name": "分组A",
	"flag": 0,
	"children": ["10081", "10083"]
},
{
	"_id": "yyy",
	"name": "分组B",
	"flag": 1,
	"children": ["分组A", "10082"]
}
{
	"_id": "zzz",
	"name": "_other",
	"flag": 1,
	"children": ["10103", "10108", "10106"]
}
```

**说明：**

* name：分组名，_other表示不属于任何一个分组
* flag：层次标志，0表示该分组在最外层，1表示该分组在另一个分组内部
* children：分组包含的设备或子分组

**Comment by zhongstar** [comment]
依据上面的初步结构设计，定义页面功能点：

**list展示**：
树状分层结构，取mongodb集合所有文档数据，根据flag和children字段划出分层结构，然后根据id取api brief数据，展示。

**添加组：**
向 collection 中 insert 一个文档操作；

**添加设备：**
根据document 的 id，向该 document 中 update children 字段（append一个hostid）；

**编辑：**
根据document 的 id，向该 document 中 update name字段

**拖拽：**
update document 的flag and children 字段，拖拽完重新加载 list 

**排序：**
有拖拽功能，排序似乎意义不大

**后期功能：**
点击链接详情弹出框


**问题1：**
自定义组名称name是用户自己定义的话，_other肯定是维护不了，所以建议加一个字段display用于用户自己定义组名称。 

**问题2：**
children中存在hostid和引用两种含义，不太合适，并且取出数据后还需要判断解析，不方便，建议拆分开来，group_children表示子组ids,host_children表示主机ids

**问题3：**
不属于任何一个分组的话用户应该也可以自定义一个其他的组，然后自己将不分组的设备添加进去，或者不添加的话说明用户自己并不关心该设备的情况。所以建议去掉_other这种分类。

{
	"_id": "xxx",
	"name": "分组A",
	"flag": 0,
        “group_children”：[“yyy”,"zzz"]
	"host_children": ["10081", "10083"]
},
{
	"_id": "yyy",
	"name": "分组B",
	"flag": 1,
         “group_children”：""
	"host_children": ["10082"]
}
{
	"_id": "zzz",
	"name": "分组C",
	"flag": 1,
        “group_children”：""
	"host_children": ["10103", "10108", "10106"]
}


这样，就可以根据上面数据结构的设直接取所有的flag为0的document 就能得到划出分层结构了。 @chenzhq
