### ISSUE TITLE
设备监控功能定义及API设计

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#23]
> ❗️以下数据的结构仅供参考，具体结构查看[RAP](http://rapapi.org/workspace/myWorkspace.do?projectId=19544#205824)

## 表格数据初始化

- [x] 异步获取设备列表的数据

- [x] 每一行的操作列表根据类型区分
**组:** 新建组，移动，编辑，删除
**设备，包括服务器，数据库等:**  移动，编辑

- [x] 每一行都包含一个icon，icon的颜色表示设备或分组状态，root组没有状态

### 成功返回数据结构

``` json
{
    "data": [
        {"cid": "classid", "pid": "父节点classid", "name": "名称", "type": "类型", "state": "状态"},
    ],
    "message": "更新成功！",
    "success": true
}
```

## 移动

* 将某一台设备或者某个分组移动到另一个位置。
* 点击弹出一个Modal框，包含设备之间的树形结构，供用户选择移动目的地
* 点击确认按钮后，出现loading动画，使用ajax向后台发送post请求，后台修改monogdb的文档，成功后更新页面dom结构，失败则给予提示，页面dom不更新

### 请求数据

移动设备

``` json
data: {
    "host": "目标设备id",
    "from_group": "设备原分组id", 
    "to_group": "目的分组id"
}
```

移动分组

``` json
data: {
    "group": "目标分组_id",
    "from_group": "原分组id",
    "to_group": "目的分组id"
}
```

### 请求成功后返回到数据格式

移动设备

``` json
{
    "data": {
        "host": "目标设备id",
        "from_group": "设备原分组id", 
        "to_group": "目的分组id"
    },
    "message": "移动成功！",
    "success": true,
}
```

移动分组

``` json
{
    "data": {
        "group": "目标分组id",
        "from_group": "原分组id",
        "to_group": "目的分组id"
    },
    "message": "移动成功！",
    "success": true,
}
```

## 新建（分组）

* 此操作按钮存在于分组行
* 点击弹出一个Modal框，包含一个input，供用户输入新分组名称
* 点击确认按钮，载入loading动画，触发post请求，成功即更新页面dom，失败给予提示

### 请求数据

``` json
data: {
    "sup_group": "父分组id",
    "new_group_name": "新分组name"
}
```

### 成功后返回的数据格式

``` json
{
    "data": {
        "sup_group": "父分组id",
        "new_group": "新分组id",
        "new_group_name": "新分组name"
    },
    "message": "新建成功！",
    "success": true,
}
```

## 删除（分组）

* 此操作按钮存在于分组行
* 点击弹出一个警告Modal框，警告是否删除该分组
* 点击确定，载入loading动画，触发`post`请求，请求成功则修改dom，失败给予提示
* 删除分组成功后，该分组下如果有成员，全部移动到上一级

### 请求数据

``` json
data: {
    "del_group": "删除分组id"
}
```

### 成功返回的数据格式

``` json
{
    "data": {
        "del_group": "删除的分组id",
        "to_group": "子成员将移动的分组"
    },
    "message": "删除成功！",
    "success": true,
}
```

**Comment by chenzhq** [comment]
## 更新记录

### 2017年6月28日 新建

> 移动，删除，新建操作的定义和API结构

### 2017年6月29日 修改

> - 增加设备列表的调用API结构
> - 增加RAP链接和少量修改

**Comment by zhongstar** [comment]
**针对设备概览模块的几个功能点实现的具体步骤：**

**列表展示：**
        如果只有一个根节点root，需要初始化数据，将所有的设备添加到root根节点的host_children中；

**新建分组：**
        1：新增一条文档到mongodb的group集合中；
        2：更新父级组的group_children，新增name进去。

**删除分组：**
       1：根据删除组cid取要删除组的group_children,host_children；
       2：根据删除组cid取该组的上一级cid，循环group_children添加到上一级的group_children中，同时更改子成员的pid为上一级cid。循环host_children添加到上一级的host_children中

**移动分组：**
       1：Group组的pid更新为to_group_id;
       2：from_group组的group_children去掉group的name；
       3：to_group组的group_children添加group的name。

**设备移动：**
       1：from_group组的host_children去掉host原设备的id；
       2：to_group组的host_children添加host原设备的id。
