### ISSUE TITLE
监控系统进度安排

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#27]
### 说明

以下功能点的细节，见Github中的issue [#17](https://github.com/chenzhq/WsMonitor/issues/17)，该issue会持续更新
每人自行评估工作量，有任何问题，在周期的前2天提出来

#### 7月24日——7月28日（7天）

1. 完成`设备详情`和`监控点详情`功能，可以走通仪表盘——设备列表——设备详情——监控点详情一套流程
2. 可以快速地使用docker完成zabbix服务器的部署

已知的难点：

1. 监控项与图形的对应
2. 展示图形的分类
3. 数据筛选

#### 7月31日——8月11日（14天）

1. 完成`业务监控`功能
2. 重新整理规划zabbix模版的内容和结构

已知的难点：

1. 业务方块的页面布局
2. 设计触发器权值以及业务平台的健康度等指标

#### 8月14日——8月25日（14天）

1. 完成`告警功能`
2. 重新配置，测试并确定zabbix的告警策略（Action）

已知的难点有：

1. zabbix触发器内容的转换
2. zabbix动作的规范设计 
3. 问题和告警的筛选和图形展示

#### 8月28日——9月8日（14天）

1. 完成`统计报表`功能
2. 重新设计细化用户权限，每个（类）用户对应不同的主机群主

已知的难点：

1. 确定可实现的报表类型
2. 多类数据的查询
3. 报表的导出功能

#### 9月11日——9月15日（7天）

1. 对系统进行集成测试
2. 优化页面中不合理的细节
3. 删除冗余代码

#### 9月15日 

完成监控系统V1.0，包括的功能点有：

1. 仪表盘：查看所有对象的运行情况
2. 设备监控：以设备为单位，查看所有设备以及其下监控点，监控项的运行情况，
3. 业务平台监控：以业务平台为单位，查看该平台的整体运行状况
4. 问题告警：查看所有问题和告警情况，并能对问题进行确认
5. 业务报表：提供简单的报表功能
6. 权限控制：为不同权限的用户提供不同的功能

除此之外，还需要：

1. 对整套系统进行了完整的测试，消除明显的问题和bug
2. 形成一套完善，快速的部署流程，包括zabbix和stoner

**Comment by chenzhq** [comment]
@zhongstar @yanms719 

上面是初步制定的计划安排，大家看一下有没有问题：包括时间不合适，功能点遗漏或者完成难度太大等。今天下午4点之前在此issue下回复
**没有问题也回复**

**Comment by zhongstar** [comment]
@chenzhq 
---

**7月24日——7月28日（7天）**

*监控点详情设计细节还未确定；*

*已知的难点：*
    1、监控项单位转换
    2、阀值的获取
    
目前只考虑了下周的情况，其他的还未发现有什么问题，发现后在提出来，确定后调整进度计划。

**Comment by yanms719** [comment]
以下三大快目前没详细设计，不知道具体做成什么样以及工作量：
1. 业务监控中，是否完成“业务分析”功能，拓扑图展示？
2. 告警功能中，告警冗余完成没？是什么形式显示：页面，邮件？
3. 统计报表

**Comment by chenzhq** [comment]
@yanms719 
这个计划是整个开发过程的计划安排，主要关注整体的时间节点是否合适，每个功能点的工作量在具体开发前再进行估算

另外，如果对某个功能点有自己对想法，欢迎提issue

**Comment by zhongstar** [comment]
---
**监控点设计细节**

***概述***
1、该监控点的配置信息：point_name,state???
2、监控项数值列表【item_name,state,value,last_time,阀值???】

***图形报告***
1、所有数值型监控项的图形展示，默认柱状图
2、展示：线图，柱状图，面积图（X轴是时间时序），筛选时间段:1天，3天，7天，30天

***时序数据***
1、所有数值型监控项时序数据列表【last_time，state，value，？？？】，（建议几个监控项就有几个table，筛选的时候联动筛选）
2、筛选条件：
    时间段：1天，3天，7天，30天；
    状态
