### ISSUE TITLE
设备详情 & 监控点详情 问题

### ISSUE THREAD

**Issue by zhongstar** [chenzhq/WsMonitor#28]
## 设备监控页面

- [x] 1.部分主机的接口信息部分数据未获取到
- [x] 2.监控点信息部分悬浮延迟时间过长，鼠标离开监控点域之后悬浮框立即消失，无法下拉   
- [x] 3.监控点信息状态颜色映射存在问题，正常为绿色，警告为黄色，严重为红色，无触发器监控项显示灰色   
- [x] 4.单位转换：单位还未显示，数值也未转换
- [x] 5.问题监控项图形部分取的是最新一天的数据，但是存在许多问题监控项最新的一天没有数据，导致显示为空，所以建议取最新的40条数据作为显示
- [x] 6.问题监控项和自定义监控项的摆放顺序建议自定义放上面，问题监控项放下面

## 监控点详情页面

- [x] 1.概述、图形报告、时序数据三个部分的数据单位接口中提供了，但是数值还未转换成可看性的数据；
- [x] 2.阀值的获取方式已经确定，但时序数据的各个状态值的获取还未确定清楚，到底是在前端处理，还是后台解析

**Comment by chenzhq** [comment]
页面上的问题，和 @yanms719 讨论修改

## 设备监控页面

> 5.问题监控项图形部分取的是最新一天的数据，但是存在许多问题监控项最新的一天没有数据，导致显示为空，所以建议取最新的40条数据作为显示

如果最近一天没有数据，说明这一天没有获取到监控数据，表示有问题，就应该显示为空。

## 监控点详情页面

> 2.阀值的获取方式已经确定，但时序数据的各个状态值的获取还未确定清楚，到底是在前端处理，还是后台解析

时序数据的状态在前端后端都可以处理，目前来看，两种方式没有绝对的好坏，你自行判断；如果要在前端实现，也主要有你来实现
