### ISSUE TITLE
监控点问题收集

### ISSUE THREAD

**Issue by yanms719** [chenzhq/WsMonitor#29]
- [x]  1.监控项点击弹出框后每次加载内容需要清空
- [x]  2. 当监控点过多的时候，页面被拉伸，需要固定长度。
- [x]  3.按钮“3天、7天、线状图”等点击后颜色未改变，需要标识
- [x]  4.监控点弹出框中，概述tab下列表不显示“是否自定义”字段；数据tab下列表不显示“指标”字段；报表tab下面积图形去掉渐变红色。
- [x]  5.监控项点击弹出框标题写在上面
- [x]  6.监控项中概述的列表，隐藏‘自定义’、‘状态’字段，用整行用颜色表示状态

**Comment by yanms719** [comment]
@chenzhq @zhongstar 发现有需要修改的，请帮助提出

**Comment by zhongstar** [comment]
**仪表板 & 设备详情 & 监控点详情 细节问题梳理**

---

-  仪表板

 *1. 仪表板页面*

- [x]   a.最新问题默认排序为最新修改时间

 - 设备详情
 
 *1. 监控点信息部分*

- [x]     a、悬浮框大小不合适，横纵都有缩进条不美观，整个监控点部分的高度不固定
**_固定长度后出现新问题：悬浮框在滚动条内被遮挡。存在BUG：鼠标滑动多个按钮悬浮框显示多次。_**
- [x]     b、所有监控项数值存在映射的还未做处理
- [ ]     c、客户端信息一直处于严重状态，基本信息中运行时间处于严重状态 不对，需要处理
- [ ]     d.磁盘信息和网卡流量信息采用了过滤处理，但是效果确实把所有的信息都过滤掉了


 *2. 主机图形展示部分*

- [x]     a、仪表盘样式调整
- [x]     b、针对数值单位为 % 的监控项才允许使用仪表盘
- [x]     c、图形中判断单位为 % 的监控项的y轴区间应设定为0-100%
- [x]     d、状态与阀值显示：
- [x]         两条线 or  状态颜色表示 ，面积图样式 
**_暂时去掉，效果不满意_**
- [x]     e、时间去掉年份
- [x]     f、添加图形时针对不同数值类型的图形选项选择还需要优化
- [x]     g、保存图形监控项时还未校验已添加过的监控项不允许再次添加，同时增加修改和删除图形的功能

 - 监控点详情

 *1. 概述*
 
  

- [x]   a、是否自定义 一栏不显示，状态采用颜色显示

    
 *2. 图形报告*
    
    

- [x] a、筛选条件选中给样式

 *3. 时序数据*  
    
    

- [x] a、指标一栏不显示，状态采用颜色显示，单位不显示
- [x]     b、监控项选择框初始值
- [x]     c、状态筛选
