### ISSUE TITLE
设备监控问题收集

### ISSUE THREAD

**Issue by yanms719** [chenzhq/WsMonitor#35]
## _业务列表_

- [x] 点击业务列表的链接还未添加，跳转至指定业务平台的业务概述部分

## _业务方块_

- [x] 图形纵坐标不显示小数部分，刻度 不含小数

- [x] 如果存在状态数量为0 的传值 null **_不必改_**

- [x] 健康度背景色和字样颜色搭配

### 业务概述

- [x] 清理页面静态数据

- [x] 图形刻度

- [x] 健康度背景色和字样颜色搭配

- [x] 分类菜单中监控项部分是否还需要添加阀值字段

### 业务树

- [x] 清空监控点列表框

- [x] 只针对主机双击事件

- [x] 添加、修改、删除集群，移动设备功能

### 业务图形报告

- [x] 图形报表用宽度用百分比，不需要拖动 

- [x] 添加、删除、修改图形item功能

- [x] 点击添加图形同时会触发收缩下拉框动作

**Comment by yanms719** [comment]
git：提交问题
错误操作：1.margin 先拉下远程 2.start feature新建分枝（处理其他临时事情。而这段时间有其他远程提交）3.commit再提交4.finish feature （这时候会提醒margin）5. push
错误原因：在提交操作前，没有保证当前文件是远程最新，finish的时候没有把分枝的起点移动在最新的最前面而导致出现默认的margin。
更正：每次提交前保证文件是最新的，或者移动分枝的起点。 @chenzhq

**Comment by chenzhq** [comment]
@yanms719 
1. 是merge（合并），不是margin
2. 你说的错误原因不准确，“提交”是指的什么？commit还是push？保证每次提交都是在最新代码上，是可以避免所有的问题，但这并不是你提交错误的根本原因，你可以思考**为什么会有合并远程分支到本地的这类操作**？

你再想想，实在想不清楚，再问我。
