### ISSUE TITLE
问题管理模块 工作计划

### ISSUE THREAD

**Issue by zhongstar** [chenzhq/WsMonitor#36]
## 业务管理模块

 - 重绘业务树，采用自定义节点方式，实现美观化
 1. G6前端页面定义绘图 节点定义 绘图布局 1天
 2. 后台数据重构，图片url获取方式 所传字段清单 0.5天
后台数据获取已完成，API已更新
 
### 【 问题列表 】
 - 初步设想问题管理模块中问题列表子模块的设计与实现方式 
 1. 整个机制还不熟悉，需要先熟悉zabbix实现机制与对象、数据存储方式【0.5天】（首先花半天时间初步熟悉了解，根据后面边做功能边熟悉zabbix端实现原理）
 2. 各个字段的获取方式和展现形式，主要针对列表字段数据【1天】
 3. 后台编码实现【2天】
 4. 前端页面实现
 5. 前后端数据对接与调试【0.5天】
 6. 确认记录 pop 功能接口【1天】
 7. 告警记录 pop 功能接口【1天】
+ 共6个工作日
### 【 问题详情 】
 1.  梳理具体的功能点和实现方式：各个字段的获取方式，哪些直接写入模板，哪些值异步获取【2天】
 2. 后台编码实现【2天】
 3. 前后端数据对接与调试【1天】
 4. 确认记录 pop 功能接口【1天】
 7. 告警记录 pop 功能接口【1天】
+ 共7个工作日
+ 理想状态下 13个工作日可完成，但是根据实际的经验都要留一周的时间做这个模块的功能及界面调整及优化，所以预计需要3周多一点的时间完成问题管理模块。

## 告警日历
+ 暂略

**Comment by yanms719** [comment]
1.问题管理页面布局 （0.5天）动态数据（1.5天）
 一个datatable，两个pop，一个button事件。
2.问题详情页面布局 （0.5天）动态数据（1.5天）
 一个table基础静态信息，一个datatable,2个pop，一个堆状图
3.日历图页面布局（1天）动态数据（2天）
 一个datatable，一个日历图。
4. 测试样式调整（3天）
5. 动态数据调整。（可能有可能无）

**Comment by yanms719** [comment]
告警图形的数据结构：问题详情页面
 var data = [
                    [1447923064, 1567933064, 1, 'green'],
                    [1567933064, 1607943064, 1, 'yellow'],
                    [1607943064, 1647953064, 1, 'red'],
                    [1547944064, 0, 0, ' '],
                    [1597955064, 0, 0, ' '],
                    [1647953064, 0, 0, ' '],
                ]
1. 数值前三个值是数值，最后一个字符串；
2.告警线，a[0]代表时间点，a[2]为0是一个标识符，代表是画线的。
3.告警块，a[0]代表起始时间，a[1]代表结束时间，a[3]代表状态的颜色。
