### ISSUE TITLE
修改任务列表

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#42]
**注意：以下任务还会更新，没法具体到每一个问题由谁去修改，看到和自己相关或者能够实现的就去做，有任何问题提出来。**
**先实现视图展示的功能，再做修改！**

@yanms719 @zhongstar

---

## 系统细节

* [x]  所有与异步获取数据相关，导致可视界面结构产生明显变化，且时间超过1s（有明显卡顿或延迟）的操作，必须在相应的组件上提供loading的遮罩层（这类修改有很多，仔细查找！）
* [x]  所有表格的列，需要有最大宽度，如果信息太长，默认只展示前面N个字（特殊情景也许有更合适的方法
* [x]  如果用颜色表示状态，在颜色的icon上提供pop框，鼠标移上去，显示正常/警告/告警
* [x]  异步获取数据时，如果用户长时间没有操作，session会被注销，这种返回的异常需要在ajax方法中进行捕获，并跳转到登录页面，不仅仅只是弹出一个提示框
* [x]  排查并删除调试用的console

## 仪表盘子tab

* [x]  业务系统tab页，名称提供链接，跳转进入**业务详情**
* [x] 设备tab页，名称提供链接，跳转进入**设备总览**，所选设备为选中状态
* [x] 监控点tab页，名称提供链接，跳转进入**设备总览**，所选监控点为选中状态

### 事件详情modal

* [x] 问题详情中需要条件返回按钮 
* [x] 问题列表中的历史记录第二次选择的时候没有经过刷新，存在bug
* [x]  事件详情modal框，需要一个标题，可用触发器描述
* [x]  给问题列表添加一个搜索框
* [x] 告警记录，区分触发告警和回复告警，可参考pop框（希望有更好的解决方法）
* [x] 告警记录，信息压缩太多，需要精简一部分，并提供查看详细告警信息的功能：1.用额外的modal显示；2.使用semantic的菜单样式；3....
* [x] 确认记录的高度如果超过了事件细节，应该提供下拉框，最大高度？
* [x] 确认中的用户动作显示的是“未确认”，应该是未关闭？
* [x] 确认记录中，时间和消息的长度控制，时间被折叠了，消息如果字数较多，能否提供查看完整信息的功能？

### 确认Modal

* [x] 输入框太小，text area更合适
* [x] checkbox的名称是问题已关闭？改为**关闭问题**，如果用户无法关闭该问题，则为不可选状态
* [x] 输入框不能为空，更好的实现方式是，输入框中没有文字时，确认按钮为不可选 **_在onApprove之前在onshow之后，判断输入框是否有值，没找到这个函数_**
* [x] 确认记录如果很多，需要提供下拉框

### 业务列表

* [x] 操作一列中，**管理**是配置业务平台下的设备，**>>**是跳转？未提供跳转链接
* [x] 状态一列的表头，加上一个？的icon，pop以下信息：当业务平台下有任意一个设备为警告/严重状态时，该平台则为警告/严重状态。（可适当修改，黑地白字）
* [x] 业务方块显示效果不佳，暂时屏蔽该功能，后面可以考虑融合到业务列表中（使用百叶窗的样式？）

### 业务详情

* [x] 增加标题**业务详情**，选择业务平台的下拉框与标题同一行
* [x] 下方详情的三列，增加分割线，加强选中状态的样式，例如右侧一个小箭头  **_由于监控点数量过超出给加了滑动条样式会覆盖“右侧一个小箭头 ”的样式，采用菜单用反色样式加强选中状态。_**
* [x] 最右侧除了一个展示监控点下所有监控项的表格外，增加一个链接，点击弹出监控点详情modal
* [x] 业务图形报告，10月9号测试图形出不来。基本操作逻辑需要修改，特别是编辑操作
* [x] 业务图形报告的删除确认操作，用的alert，修改

**Comment by zhongstar** [comment]
@yanms719 
1. 轮播视图中表格插件设置行列数和实际给出的行列数不一致，总是三列
2. 全屏轮播中head部分样式还未完成

**Comment by zhongstar** [comment]
1. 修改列表中的任务，疑问
2. 中英映射，asyncAPI返回的数据不含中文，同步修改RAP
3. 前端重构，保证高重用性，例如echarts的option，尽量同一个页面，同一种类型，甚至整个系统共用。需要花时间学习前端模块化的知识，包括**ES6**，webpack，**webstrom**等，至少得做到了解。这类重构不马上实施，多思考前端页面的操作逻辑，搞清楚从哪里下手
4. 总结自己在前几个月的工作过程中遇到的问题，特别是当时放下未解决的问题，同时需要提出自己的看法和解决方案
5. 编码过程中，为了达到某种目的，如果用到了一些hack技术，记录下来
6. 最多2天一次会议，15-30分钟，尽量在早上，介绍昨天的工作和今天准备做的工作，可以直接讲解代码

**Comment by chenzhq** [comment]
## 设备管理

### 设备总览

1. 标题（类似这类错误 @yanms719 多花点时间，把整个系统的流程过几遍，不要再出现这种非常明显的界面问题）
2. 点击监控点弹出Modal
3. 监控点和设备加上有pop功能，可以使用`设备详情`里的监控点pop框
4. 左上角的统计，去掉后空了一块，不好看，补充相应的API，将这部分功能加进去
5. 关于重构此页面的功能，由于一些功能需要完全重写，暂时放下，第二阶段再作为优先实现的任务

### 设备详情

1. 连接详情（左上）样式基本成型了，如果有时间，可以把这些数据改为异步获取，如果时间较紧，仍然采用模版变量的方式重构
2. 监控点详情，pop框还是会被遮挡住，如果没有解决方法，则去掉
3. 此页面右上提供一个按钮（下拉框），弹出设备选择的树形菜单，类似业务详情；基于这个修改，标题样式可能需要调整

### 监控点Modal

未发现明显问题

**Comment by zhongstar** [comment]
## 剩余待解决问题
1. 设备详情右上角联动下拉框
2. 设备概览pop，跳转连接定位
3. 轮播配置图形报告配置框样式调整
4. 告警记录标题和内容的显示
5. 静态表格图形类型引入
6. 还有多的时间的话调整下轮播样式
