### ISSUE TITLE
剩余问题

### ISSUE THREAD

**Issue by yanms719** [chenzhq/WsMonitor#45]
1. 业务详情页面，图形删除后的提醒内容，data-name没获取到，继续找原因，实在不行不显示名称。

- [x] 2. 设备总览，pop很不协调
 产生原因是pop是鼠标移动上去的显示的，而现在的又在pop外面家里鼠标的hover事件，不加hover事件又获取不到设备的id。

3. 轮播页面图形配置2列菜单、业务详情下3列菜单
- [x] 文字超出使用css样式隐藏了，但此处使用pop无效，缺少鼠标移动上去显示全部信息的效果。
PS：轮播页面图形配置2列菜单在操作的时候好像存在逻辑问题（没清空？），需测试确定。

- [x] 4. 主机详情
没必要的alert框，使用样式还提醒不能为空，但在改动的时候发现有点逻辑不对……需测试调整。

**Comment by yanms719** [comment]
文字过长隐藏显示方式
一、table
（1）隐藏
<table class="ui fixed single line table"></table>
固定单行显示“fixed single line”超出文字自动隐藏；

（2）显示
<td title='"+data[i].value +"'> " +data[i].value+"</td>
属性“title”，超出文字鼠标移动上去显示

二、非table
（1）隐藏
.text-hidden{
				overflow: hidden; /*自动隐藏文字*/
				text-overflow: ellipsis;/*文字隐藏后添加省略号*/
				white-space: nowrap;/*强制不换行*/
			}
添加CSS样式，超出文字自动隐藏；

（2）显示
<a class='item text-hidden' title='"+data[i].point_name+"'></a>
属性“title”，超出文字鼠标移动上去显示，如轮播页面图形配置2列菜单、业务详情下3列菜单。
<div  data-tooltip='"+title+"'>
属性“data-tooltip”，超出文字鼠标移动上去显示，只有部分标签有效。

**Comment by zhongstar** [comment]
@yanms719 以上问题已解决，请测试，另外整个项目还有多处ALERT框，设备详情的删除、监控视图的操作、轮播配置的操作等等，删除的modal框是不是太大了？
