### ISSUE TITLE
实现计算不同状态主机数量的API

### ISSUE THREAD

**Issue by chenzhq** [chenzhq/WsMonitor#8]
已经在HostService及impl类中实现类部分，可参考完成剩下的部分

**可能需要实现部分bix4j程序**

如果对设计部分（如何获取不同状态的主机等）有疑问，在此issue下直接回复

**Comment by zhongstar** [comment]
@chenzhq  
1、countUnsupportedHost获取这个状态的主机数量改如何获取？
2、countOkHost获取方式？
有时间的话讨论下。

**Comment by chenzhq** [comment]
## 已废弃，新的查看 #13 
## 主机所有状态之间的关系 

zabbix主机状态图
![image](https://cloud.githubusercontent.com/assets/8817002/26707620/b087f6aa-4778-11e7-929b-5e75016edf90.png)

**停用**：默认排除，根据`monitored_hosts `字段筛选，返回结果不包含停用主机
**维护（无数据采集）**：根据`maintenance_status`和`maintenance_type `筛选，维护暂时只允许使用无数据采集的方式
**维护（有数据采集）**：同上，但触发器会产生事件以及问题，目前不允许配置这种维护
**问题**：主机下的触发器产生了问题，即为危险状态，根据产生问题的触发器筛选危险状态主机
**不可用**：四种监控方式有一种为不可用，即为不可用；不可用状态为配置问题，并不代表监控设备运行有问题，因此不对该状态进行筛选，合并到正常主机种；后期增加新的功能，供用户查看不可用状态的主机
**正常**：除去以上状态的其他主机为正常主机（包括不可用），总的主机数量-其它状态主机数

设计后的主机状态图如下
![image](https://cloud.githubusercontent.com/assets/8817002/26707846/37ac09d6-477a-11e7-8d4a-140aea6c79ce.png)

因此目前传到前端展示的状态只需要**正常，问题，维护**三种状态。
